# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96a499ff0633db8ae53502a4f9a8093266d1302cbebb5d9097c582d0c1211d2c66f895a243687a769ba7d3415154a163bb93cc7658b0cb13d477674c5eb6deba

test:
  secret_key_base: bd7049ec32ebd6ca6ed301c8f30cd51ee19baf403c01066647a417a6756c6e889bc2c75a320f835b65a72a79122bc73f6c236ad590db0dcf16754c5bef3f0178

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
